# Generated by Django 5.1.3 on 2024-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_stocks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refkey',
            name='key',
            field=models.CharField(unique=True),
        ),
    ]
