# Generated by Django 5.1.3 on 2024-11-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_refkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refkey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_keys', to='main_app.users'),
        ),
    ]
