# Generated by Django 5.1.3 on 2024-11-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cars_gos_number_alter_cars_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active_stocks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_mess', to='main_app.users')),
            ],
            options={
                'verbose_name': 'Appeals',
                'verbose_name_plural': 'Appeals',
            },
        ),
    ]
