# Generated by Django 5.1.3 on 2024-12-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_appeals_user_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='self_worker',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='VeryGoodDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_drive', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VeryGoodDriver', to='main_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='YourTaxiPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_money', models.IntegerField(blank=True, null=True)),
                ('count_invite', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='your_taxipark', to='main_app.users')),
            ],
        ),
    ]
