# Generated by Django 5.1.3 on 2024-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_users_fleet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fleet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
