# Generated by Django 5.1.3 on 2024-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_users_fleet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='card_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
