# Generated by Django 5.1.3 on 2024-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_users_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whom', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=2048)),
            ],
        ),
    ]
