# Generated by Django 5.1.3 on 2024-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_activemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemessage',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activemessage',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activemessage',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
