# Generated by Django 5.1.3 on 2024-12-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_users_address_alter_users_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fleet_id',
        ),
        migrations.AddField(
            model_name='users',
            name='fleetid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
