# Generated by Django 5.1.3 on 2024-12-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_tariffs_users_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='service_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='is_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.users')),
            ],
            options={
                'verbose_name': 'User Credentials',
                'verbose_name_plural': 'User Credentials',
            },
        ),
    ]
