# Generated by Django 5.1.3 on 2024-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_tariffs_service_id_alter_tariffs_is_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffs',
            old_name='service_id',
            new_name='serviceid',
        ),
        migrations.AlterField(
            model_name='users',
            name='self_worker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
