# Generated by Django 5.1.3 on 2024-12-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_service_id_tariffs_serviceid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='user',
        ),
    ]
