# Generated by Django 5.1.3 on 2024-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_usercredentials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_swap_tariff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verygooddriver',
            name='total_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
